# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: datastream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'datastream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x61tastream.proto\x12\ndatastream\"F\n\rStreamRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\nmax_frames\x18\x02 \x01(\x05\x12\x11\n\tstream_id\x18\x03 \x01(\x05\"\x0f\n\rHealthRequest\"B\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"\x98\x01\n\nDataStream\x12(\n\x04rows\x18\x01 \x03(\x0b\x32\x1a.datastream.SpectrogramRow\x12\x17\n\x0f\x63urrent_max_amp\x18\x02 \x01(\x01\x12\x17\n\x0f\x63urrent_min_amp\x18\x03 \x01(\x01\x12\x14\n\x0c\x66rame_number\x18\x04 \x01(\x03\x12\x18\n\x10server_timestamp\x18\x05 \x01(\x03\"~\n\x0eSpectrogramRow\x12\x10\n\x08\x63\x61nvasId\x18\x01 \x01(\t\x12,\n\x07sensors\x18\x02 \x03(\x0b\x32\x1b.datastream.SensorIntensity\x12\x16\n\x0estartTimestamp\x18\x03 \x01(\x03\x12\x14\n\x0c\x65ndTimestamp\x18\x04 \x01(\x03\"0\n\x0fSensorIntensity\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tintensity\x18\x02 \x03(\x02\x32\xa8\x01\n\x11\x44\x61taStreamService\x12K\n\x12StreamSpectrograms\x12\x19.datastream.StreamRequest\x1a\x16.datastream.DataStream\"\x00\x30\x01\x12\x46\n\x0b\x43heckHealth\x12\x19.datastream.HealthRequest\x1a\x1a.datastream.HealthResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datastream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMREQUEST']._serialized_start=32
  _globals['_STREAMREQUEST']._serialized_end=102
  _globals['_HEALTHREQUEST']._serialized_start=104
  _globals['_HEALTHREQUEST']._serialized_end=119
  _globals['_HEALTHRESPONSE']._serialized_start=121
  _globals['_HEALTHRESPONSE']._serialized_end=187
  _globals['_DATASTREAM']._serialized_start=190
  _globals['_DATASTREAM']._serialized_end=342
  _globals['_SPECTROGRAMROW']._serialized_start=344
  _globals['_SPECTROGRAMROW']._serialized_end=470
  _globals['_SENSORINTENSITY']._serialized_start=472
  _globals['_SENSORINTENSITY']._serialized_end=520
  _globals['_DATASTREAMSERVICE']._serialized_start=523
  _globals['_DATASTREAMSERVICE']._serialized_end=691
# @@protoc_insertion_point(module_scope)
