# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import datastream_pb2 as datastream__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in datastream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataStreamServiceStub(object):
    """=============================================================================
    Service Definition
    =============================================================================

    Main service for streaming spectrogram data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSpectrograms = channel.unary_stream(
                '/datastream.DataStreamService/StreamSpectrograms',
                request_serializer=datastream__pb2.StreamRequest.SerializeToString,
                response_deserializer=datastream__pb2.DataStream.FromString,
                _registered_method=True)
        self.CheckHealth = channel.unary_unary(
                '/datastream.DataStreamService/CheckHealth',
                request_serializer=datastream__pb2.HealthRequest.SerializeToString,
                response_deserializer=datastream__pb2.HealthResponse.FromString,
                _registered_method=True)


class DataStreamServiceServicer(object):
    """=============================================================================
    Service Definition
    =============================================================================

    Main service for streaming spectrogram data
    """

    def StreamSpectrograms(self, request, context):
        """Stream spectrogram data for a given job
        Returns a continuous stream of DataStream messages until:
        - Client disconnects
        - Job completes (historic mode)
        - Timeout (180 seconds of inactivity)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """Health check endpoint (optional)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSpectrograms': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSpectrograms,
                    request_deserializer=datastream__pb2.StreamRequest.FromString,
                    response_serializer=datastream__pb2.DataStream.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=datastream__pb2.HealthRequest.FromString,
                    response_serializer=datastream__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datastream.DataStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datastream.DataStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataStreamService(object):
    """=============================================================================
    Service Definition
    =============================================================================

    Main service for streaming spectrogram data
    """

    @staticmethod
    def StreamSpectrograms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datastream.DataStreamService/StreamSpectrograms',
            datastream__pb2.StreamRequest.SerializeToString,
            datastream__pb2.DataStream.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datastream.DataStreamService/CheckHealth',
            datastream__pb2.HealthRequest.SerializeToString,
            datastream__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
