# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pandadatastream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pandadatastream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pandadatastream.proto\x12\x0fpandadatastream\"\xa2\x02\n\nDataStream\x12\x15\n\rstart_channel\x18\x01 \x01(\x05\x12\x13\n\x0b\x65nd_channel\x18\x02 \x01(\x05\x12\x1a\n\x12timestamp_in_milis\x18\x03 \x03(\x03\x12\x11\n\trow_index\x18\x04 \x03(\x05\x12\x14\n\x0c\x64\x61ta_shape_x\x18\x05 \x01(\x05\x12\x14\n\x0c\x64\x61ta_shape_y\x18\x06 \x01(\x05\x12\x19\n\x0c\x64\x61ta_shape_z\x18\x0b \x01(\x05H\x00\x88\x01\x01\x12\x16\n\x0eglobal_maximum\x18\x07 \x01(\x02\x12\x16\n\x0eglobal_minimum\x18\x08 \x01(\x02\x12\x11\n\tmain_data\x18\t \x03(\x0c\x12\x13\n\x06job_id\x18\n \x01(\x05H\x01\x88\x01\x01\x42\x0f\n\r_data_shape_zB\t\n\x07_job_id\"&\n\x11StreamDataRequest\x12\x11\n\tstream_id\x18\x01 \x01(\x05\x32\x66\n\x11\x44\x61taStreamService\x12Q\n\nStreamData\x12\".pandadatastream.StreamDataRequest\x1a\x1b.pandadatastream.DataStream\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pandadatastream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATASTREAM']._serialized_start=43
  _globals['_DATASTREAM']._serialized_end=333
  _globals['_STREAMDATAREQUEST']._serialized_start=335
  _globals['_STREAMDATAREQUEST']._serialized_end=373
  _globals['_DATASTREAMSERVICE']._serialized_start=375
  _globals['_DATASTREAMSERVICE']._serialized_end=477
# @@protoc_insertion_point(module_scope)
